server:
  port: 8110

db:
  hostname: localhost
  username: root
  password: 12345678
  schema: pdftag

spring:
  application:
    name: pdftag
  r2dbc:
    url: r2dbc:pool:mysql://${db.hostname}:3306/${db.schema}?autoreconnect=true&useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true
    username: ${db.username}
    password: ${db.password}
  flyway:
    url: jdbc:mysql://${db.hostname}:3306/${db.schema}
    user: ${spring.r2dbc.username}
    password: ${spring.r2dbc.password}
    baseline-on-migrate: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
      cors:
        allowed-origins: "*"
        allowed-methods: "*"
logging:
  level:
    root: debug
  file:
    max-history: 2
peacetrue:
  spring:
    security:
      ignored-urls: ['/users/register','/users/exists','/index.html','/manifest.json','/logo192.png','/static/**']
  #  file:
  #    base-path: /Users/xiayx/Documents/Projects/pdftag/01-upload
  enum:
    base-package-paths: com.mi.pdftag
  operator:
    pointcut:
      expression: 'execution(* com.mi.pdftag..*ServiceImpl.*(*,..))||execution(* com.github.peacetrue..*ServiceImpl.*(*,..))'
  file:
    base-path: /Users/xiayx/Documents/Projects/pdftag/02-output

