server:
  port: 8110

db:
  hostname: localhost
  username: root
  password: 12345678
  schema: pdftag

logging:
  level:
    root: debug
  file:
    max-history: 2

com:
  mi:
    pdf-tag:
      dita-base-dir:
        default: /Users/xiayx/Documents/Projects/pdftag/docs/antora/modules/ROOT/attachment/dita-ot-2.3
        chinese: /Users/xiayx/Documents/Projects/pdftag/docs/antora/modules/ROOT/attachment/dita-ot-2.3
        english: /Users/xiayx/Documents/Projects/pdftag/docs/antora/modules/ROOT/attachment/dita-ot-2.3
      output-dir: /Users/xiayx/Documents/Projects/pdftag/02-output
      reproduction-customization-dir: /Users/xiayx/Documents/Projects/learn-dita-ot/src/test/resources/watermark
