server:
  port: 80

db:
  hostname: localhost
  username: root
  password: 12345678
  schema: pdftag

logging:
  level:
    root: info
  file:
    path: /root/peacetrue/pdftag/03-logs
    max-history: 2

peacetrue:
  file:
    base-path: /root/peacetrue/pdftag/01-upload

com:
  mi:
    pdf-tag:
      dita-base-dir: /root/peacetrue/pdftag
      output-dir: pdf
      reproduction-customization-dir: /root/peacetrue/pdftag/watermark
      axf-path: /usr/AHFormatterV70
spring:
  session:
    timeout: 7d
